data_dir: data/
batch_size: 64
n_leading_observations: 5
crop_side_length: 128
load_from_hdf5: true
num_workers: 8
remove_duplicate_features: true
features_to_keep: null
n_leading_observations_test_adjustment: 5